apiVersion: apps/v1
kind: Deployment
metadata:
  name: XYZ-Corp-Web-App-deployment
  labels:
    app: XYZ-Corp-Web-App
spec:
  selector:
    matchLabels:
      app: XYZ-Corp-Web-App
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: XYZ-Corp-Web-App
    spec:
      containers:
       —name: XYZ-Corp-Web-App
          image: xyzcorpdigitalacr.azurecr.io/xyzcorpdigitalacr:latest
          ports:
           —containerPort: 80
=======================
apiVersion: v1
kind: Service
metadata:
  name: XYZ-Corp-load-balancer
  labels:
    app: XYZ-Corp-webapp-nginx
spec:
  type: LoadBalancer
  ports:
	—port: 80
	 targetPort: 80
   
  selector:
    app: XYZ-Corp-webapp-nginx
